version: '3.8'

services:
  backend:
    image: slawekradzyminski/jwt-auth-service
    restart: always
    ports:
      - "4000:4000"
    hostname: backend

  frontend:
    image: slawekradzyminski/frontend
    restart: always
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus